---
- name: install HAProxy and http
  package:
    name: 
      - httpie
      - haproxy 
    state: latest

- name: configure haproxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart-haproxy

- name: enable HAProxy
  service:
    name: haproxy
    enabled: true
    state: started

